name: Comment on issues
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment:
    if: context.comment.body == /*
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 This is a test comment - you ran a slash command'
            })
