name: Screenshot on comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment:
    if: startsWith(github.event.comment.body, '/screenshot')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        id: create-comment
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            return await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⌛ Getting your screenshot...'
            });
      - uses: actions/checkout@v2
      - uses: ./run-cypress
        with:
          comment: ${{github.event.comment.body}}
          comment_id: ${{github.event.comment.id}}
          s3_access_key: ${{secrets.S3_ACCESS_KEY}}
          s3_secret_key: ${{secrets.S3_SECRET_KEY}}
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const createCommentResponse = ${{steps.create-comment.outputs.result}};
            github.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: createCommentResponse.data.id,
              body: '![screenshot](https://tomdaly-gh-actions-test.s3-eu-west-1.amazonaws.com/screenshot-${{github.event.comment.id}}.png)'
            });
