name: Comment on issues
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment:
    if: startsWith(github.event.comment.body, '/screenshot')
    runs-on: ubuntu-latest
    steps:
      - uses: ./run-cypress
        with:
          COMMENT: github.event.comment.body
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📸 Took a screenshot'
            })
